version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: ezinfra-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ezinfra_development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: ezinfra-web
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root

volumes:
  db_data:
