default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'Aseem@abc3' %>
  host: <%= ENV["DATABASE_HOST"] || "127.0.0.1" %>
  port: 3306
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ezinfra_development

test:
  <<: *default
  host: 127.0.0.1
  database: ezinfra_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: ezinfra_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
