name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ezinfra_test
          MYSQL_ROOT_USER: root
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 2.7.8
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      # - name: Prepare database config
      #   run: cp config/database.yml.ci config/database.yml

      # - name: Wait for MySQL to be ready
      #   run: |
      #     until mysqladmin ping -h mysql --silent; do
      #       echo "Waiting for MySQL..."
      #       sleep 3
      #     done

      - name: Set up database for test environment
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
        run: |
          # sudo /etc/init.d/mysql start
          # mysql -e 'CREATE DATABASE ezinfra_test;' -uroot -proot
          # mysql -e 'SHOW DATABASES;' -uroot -proot
          # RAILS_ENV=test bundle exec rake db:create
          # RAILS_ENV=test bundle exec rake db:migrate
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: |
          RAILS_ENV=test bundle exec rspec  # or `rails test` if using Minitest

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update -qq
    #     sudo apt-get install -y libmysqlclient-dev nodejs
    #     bundle install

# mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_ROOT_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
